name = "TMTapeToNumber"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TMTapeToNumber"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev = "main"

[[lean_lib]]
name = "TMTapeToNumber"

[[lean_exe]]
name = "tm_tape_to_number"
root = "Main"

[[lean_exe]]
name = "checkdecls"
srcDir = "blueprint"
root = "CheckDecls"
